import { StyleSheet } from "react-native";

const loginRegisterStyles = StyleSheet.create({
  container: {
    backgroundColor: "#f0f0f0",
  },
  scrollViewContainer: {
    alignItems: "center",
    justifyContent: "center",
  },
  headerContainer: {
    alignItems: "center",
    marginBottom: 20,
    borderBottomColor: "#3c0a6b",
    borderBottomWidth: 2,
    borderStyle: "solid",
    paddingVertical: 15,
    width: "100%",
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#3c0a6b",
    marginBottom: 10,
    textAlign: "center",
  },
  card: {
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 10,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 5,
    width: "90%",
  },
  inpt: {
    backgroundColor: "#fff",
    padding: 10,
    borderRadius: 5,
    marginBottom: 16,
    fontSize: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 5,
    marginTop: 15,
  },
  inpts: {
    fontSize: 18,
    borderWidth: 1,
    width: 300,
    paddingVertical: 5,
    borderRadius: 7,
    paddingHorizontal: 10,
    marginVertical: 5,
  },
  passwordContainer: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 7,
    borderColor: "#000",
    width: 300,
    marginVertical: 5,
    padding: 0,
  },
  passwordInput: {
    flex: 1,
    marginVertical: 0,
    borderWidth: 0,
  },
  eyeIcon: {
    paddingHorizontal: 10,
  },
  press: {
    backgroundColor: "#3c0a6b",
    padding: 15,
    borderRadius: 5,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 5,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 7,
  },
  text: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
    fontWeight: "semibold",
  },
  textCenter: {
    textAlign: "center",
    marginBottom: 10,
    fontSize: 16,
    color: "#333",
  },
  link: {
    alignItems: "center",
    marginTop: 10,
  },
  linkText: {
    color: "#3c0a6b",
    textDecorationLine: "underline",
    textAlign: "center",
    fontSize: 16,
  },
});

export default loginRegisterStyles